# Generated by Django 4.2.6 on 2023-10-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='schoolmember',
            options={'ordering': ['id']},
        ),
    ]
